from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SAMPLE_PATH = ROOT / "02_sampling" / "journal_sample.csv"
POLICY_PATH = ROOT / "04_journal_policy_coding" / "policy_coding.csv"
ARTICLE_PATH = ROOT / "06_article_coding" / "article_contribution_coding.csv"
RESULTS_PATH = Path(__file__).with_name("results_summary.md")
TABLES_DIR = Path(__file__).with_name("tables")


def read_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def summarize_sample(sample_rows: list[dict]) -> list[dict]:
    counts = Counter(row.get("primary_category", "") for row in sample_rows if row.get("journal_id"))
    return [
        {"primary_category": category, "journal_count": count}
        for category, count in sorted(counts.items())
    ]


def summarize_policy(policy_rows: list[dict]) -> list[dict]:
    code_fields = [
        "originality_language",
        "novelty_language",
        "debate_entry_language",
        "specialist_legibility",
        "scope_fit_language",
        "anti_expository_language",
        "synthesis_mapping_language",
        "article_type_flexibility",
        "review_transparency",
        "architectonic_vocabulary",
        "overall_reviewability_orientation",
    ]
    summary: list[dict] = []
    for field in code_fields:
        counts = Counter(row.get(field, "") for row in policy_rows if row.get(field, ""))
        for value, count in sorted(counts.items()):
            summary.append({"code_category": field, "code_value": value, "count": count})
    return summary


def summarize_articles(article_rows: list[dict]) -> tuple[list[dict], list[dict]]:
    contribution_counts = Counter(
        row.get("primary_contribution_type", "")
        for row in article_rows
        if row.get("primary_contribution_type", "")
    )
    by_strength: dict[str, Counter] = defaultdict(Counter)
    for row in article_rows:
        strength = row.get("architectonic_strength", "")
        confidence = row.get("coding_confidence", "")
        if strength:
            by_strength[strength][confidence or "unspecified"] += 1

    contribution_rows = [
        {"primary_contribution_type": value, "count": count}
        for value, count in sorted(contribution_counts.items())
    ]
    strength_rows = []
    for strength, counter in sorted(by_strength.items()):
        for confidence, count in sorted(counter.items()):
            strength_rows.append(
                {
                    "architectonic_strength": strength,
                    "coding_confidence": confidence,
                    "count": count,
                }
            )
    return contribution_rows, strength_rows


def write_summary(sample_rows: list[dict], policy_rows: list[dict], article_rows: list[dict]) -> None:
    lines = [
        "# Results Summary",
        "",
        "This file is generated by `07_analysis/analysis.py`.",
        "",
        f"- Sampled journals: {sum(1 for row in sample_rows if row.get('journal_id'))}",
        f"- Policy-coded journals: {sum(1 for row in policy_rows if row.get('journal_id'))}",
        f"- Article-coded rows: {sum(1 for row in article_rows if row.get('article_id'))}",
        "",
        "Sensitivity analysis placeholders are available once article coding data is populated.",
    ]
    RESULTS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    sample_rows = read_rows(SAMPLE_PATH)
    policy_rows = read_rows(POLICY_PATH)
    article_rows = read_rows(ARTICLE_PATH)

    write_csv(
        TABLES_DIR / "table_1_journal_sample_by_category.csv",
        ["primary_category", "journal_count"],
        summarize_sample(sample_rows),
    )
    write_csv(
        TABLES_DIR / "table_2_policy_code_distribution.csv",
        ["code_category", "code_value", "count"],
        summarize_policy(policy_rows),
    )
    contribution_rows, strength_rows = summarize_articles(article_rows)
    write_csv(
        TABLES_DIR / "table_4_contribution_types.csv",
        ["primary_contribution_type", "count"],
        contribution_rows,
    )
    write_csv(
        TABLES_DIR / "table_7_architectonic_strength_by_confidence.csv",
        ["architectonic_strength", "coding_confidence", "count"],
        strength_rows,
    )
    write_summary(sample_rows, policy_rows, article_rows)
    print(f"Wrote analysis outputs to {TABLES_DIR}")


if __name__ == "__main__":
    main()